# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'RealTimeSports' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealTimeSports
  pod 'Alamofire'
  pod 'PureLayout'
  pod 'lottie-ios'
end
